name: Deploy Hugo site to Pages
on:
  # workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.2'
          extended: true

      - name: Build Hugo
        run: hugo -b "https://junsircoding.github.io/" -e "production"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOG_DEP_TOKEN }}
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
